name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    job_one:
        name: Deploy
        runs-on: ubuntu-latest
        steps: 
        - name: probando ip server ssh conexion
          uses: appleboy/ssh-action@master
          with:
            host: http://162.243.161.120
            username: katherinerios
            key: ${{ secrets.NODEGIT_SECRET }}
            port: 3000
            script: |
            cd ~/my-express-app/
                  git pull
                  npm install
                  pm2 restart app.js