name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    job_one:
        name: Deploy
        runs-on: ubuntu-bionic

        steps: 
        - name: probando ip server ssh conexion
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST_SECRET }}
            username: developer
            key: ${{ secrets.NG_SECRET }}
            port: 3000
            script: |
              cd test-nodegit
              git pull origin master
              git status
