name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    job_one:
        name: Deploy
        runs-on: ubuntu-latest
        steps: 
        - name: probando ip server ssh conexion
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.SSH_HOST}}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.NODEGIT_SECRET }}
            port: 3000
            script: |
              cd test-nodegit
              git pull origin master
              git status