name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    job_one:
        name: Deploy
        runs-on: ubuntu-18.04

        steps: 
        - name: probando ip server ssh conexion
          uses: appleboy/ssh-action@master
          with:
            key: ${{ secrets.KEY_SECRET }}
            username: developer
            host: 162.243.161.120        
            port: 22
            script: |
              cd nodegit/api
              git pull origin master
              git status
              killall node
              node index.js
